'use client'

import { useState } from 'react'
import { ArrowUpRight, CalendarDays, ChevronRight, Heart, MapPin, Menu, Search, SlidersHorizontal, Sparkles, Star, UserRound, X } from 'lucide-react'
import dynamic from 'next/dynamic'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'

const ClubMap = dynamic(() => import('@/components/club-map'), { ssr: false })
const Concierge = dynamic(() => import('@/components/concierge'), { ssr: false })

export const clubs = [
  { id: 'bath', name: 'The Bath Club', address: '5937 Collins Ave, Miami Beach, FL 33140', area: 'Mid-Beach', type: 'Beach club', lat: 25.8429, lng: -80.1208, color: '#d86f55', rating: '4.9', price: '$$$$', note: 'Oceanfront wellness & dining' },
  { id: 'surf', name: 'The Surf Club', address: '9011 Collins Ave, Surfside, FL 33154', area: 'Surfside', type: 'Social club', lat: 25.8789, lng: -80.1212, color: '#2d5a5a', rating: '4.8', price: '$$$$', note: 'A timeless coastal institution' },
  { id: 'fisher', name: 'Fisher Island Club', address: '1 Fisher Island Dr, Miami Beach, FL 33109', area: 'Fisher Island', type: 'Private island', lat: 25.7587, lng: -80.1409, color: '#bf965b', rating: '4.9', price: '$$$$', note: 'Island living, steps from downtown' },
  { id: 'soho', name: 'Soho Beach House', address: '4385 Collins Ave, Miami Beach, FL 33140', area: 'Mid-Beach', type: 'Members club', lat: 25.8154, lng: -80.1227, color: '#385d7a', rating: '4.7', price: '$$$', note: 'Creative energy by the sea' },
]

export default function Page() {
  const [active, setActive] = useState('bath')
  const [profileOpen, setProfileOpen] = useState(false)
  const [saved, setSaved] = useState(false)
  const activeClub = clubs.find((club) => club.id === active) ?? clubs[0]

  return (
    <main className="min-h-screen bg-[#f5f4ef] text-[#17343b]">
      <header className="sticky top-0 z-30 flex h-[76px] items-center justify-between border-b border-[#dfe3dc]/80 bg-[#faf9f5]/90 px-5 backdrop-blur-xl md:px-9">
        <a href="#explore" className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-full bg-[#17343b] text-sm font-bold text-[#f4c8aa] shadow-sm">C</div><span className="font-serif text-xl tracking-tight">Clubhouse<span className="text-[#d86f55]">.</span></span></a>
        <nav className="hidden items-center gap-8 text-sm text-[#668080] md:flex"><a className="font-semibold text-[#17343b]" href="#explore">Explore</a><a href="/collections" className="transition-colors hover:text-[#17343b]">Collections</a><a href="/about" className="transition-colors hover:text-[#17343b]">The edit</a></nav>
        <div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="hidden rounded-full md:inline-flex" aria-label="Saved clubs" onClick={() => setSaved(!saved)}><Heart className={cn(saved && 'fill-[#d86f55] text-[#d86f55]')} /></Button><Button variant="outline" className="hidden rounded-full border-[#cad5d0] bg-white/60 md:inline-flex" onClick={() => setProfileOpen(true)}><UserRound data-icon="inline-start" />Profile</Button><Button variant="ghost" size="icon" className="rounded-full md:hidden" onClick={() => setProfileOpen(true)} aria-label="Open menu"><Menu /></Button></div>
      </header>

      <section id="explore" className="mx-auto max-w-[1500px] px-4 py-7 md:px-8 md:py-10">
        <div className="mb-7 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.22em] text-[#d86f55]"><Sparkles size={14} /> The Miami edit</div><h1 className="max-w-3xl font-serif text-[clamp(2.8rem,6vw,5.4rem)] leading-[.92] tracking-[-.045em]">Find your next <em className="font-normal text-[#d86f55]">club.</em></h1><p className="mt-4 max-w-lg text-sm leading-6 text-[#718481] md:text-base">A considered guide to Miami&apos;s most magnetic private spaces, from the sand to the bay.</p></div><div className="flex items-center gap-2"><div className="relative w-full md:w-64"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[#8ca09b]" size={16} /><Input placeholder="Search a neighborhood" className="h-11 rounded-full border-[#d7dfd9] bg-white pl-9 shadow-sm" /></div><Button variant="outline" size="icon" className="size-11 shrink-0 rounded-full border-[#d7dfd9] bg-white shadow-sm" aria-label="Filter clubs"><SlidersHorizontal /></Button></div></div>
        <div className="mb-5 flex flex-wrap gap-2"><Badge className="rounded-full bg-[#17343b] px-4 py-2 font-medium text-white hover:bg-[#17343b]">All clubs</Badge><Badge variant="outline" className="rounded-full border-[#d7dfd9] bg-white px-4 py-2 font-medium text-[#668080]">Beachfront</Badge><Badge variant="outline" className="rounded-full border-[#d7dfd9] bg-white px-4 py-2 font-medium text-[#668080]">Wellness</Badge><Badge variant="outline" className="rounded-full border-[#d7dfd9] bg-white px-4 py-2 font-medium text-[#668080]">Dining</Badge></div>
        <div className="grid min-h-[650px] overflow-hidden rounded-[30px] border border-[#dde4dd] bg-white shadow-[0_24px_70px_rgba(35,61,56,0.11)] lg:grid-cols-[1.15fr_0.85fr]">
          <div className="relative min-h-[440px] bg-[#cbd8d3] lg:min-h-0"><ClubMap clubs={clubs} activeId={active} onSelect={setActive} /><div className="absolute left-5 top-5 flex items-center gap-2 rounded-full border border-white/70 bg-white/90 px-4 py-2.5 text-xs font-semibold shadow-lg backdrop-blur"><span className="size-2 rounded-full bg-[#d86f55]" /> Miami Beach · 4 clubs</div><div className="absolute right-5 top-5 hidden rounded-full border border-white/70 bg-white/90 px-4 py-2.5 text-xs font-medium text-[#668080] shadow-lg backdrop-blur sm:block"><MapPin size={13} className="mr-1 inline" /> Drag to explore</div><div className="absolute bottom-5 left-5 rounded-2xl bg-[#17343b]/95 px-4 py-3 text-xs text-white shadow-lg"><span className="mr-2 inline-block size-2 rounded-full bg-[#f4c8aa]" /> Hover a listing to fly there</div></div>
          <aside className="flex flex-col bg-[#fcfbf8] p-5 md:p-7"><div className="mb-5 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#8ba09a]">Handpicked today</p><h2 className="mt-1 font-serif text-3xl tracking-tight">Featured clubs</h2></div><span className="text-xs font-medium text-[#9aada8]">01—04</span></div><div className="flex flex-1 flex-col gap-2">{clubs.map((club, index) => <button key={club.id} onMouseEnter={() => setActive(club.id)} onFocus={() => setActive(club.id)} onClick={() => setActive(club.id)} className={cn('group flex w-full items-start gap-3 rounded-2xl border p-3.5 text-left transition-all duration-300', active === club.id ? 'border-[#e8a28e] bg-[#fff5f1] shadow-[0_8px_20px_rgba(216,111,85,.1)]' : 'border-transparent hover:border-[#dce5df] hover:bg-white')}><span className="grid size-9 shrink-0 place-items-center rounded-full text-xs font-semibold text-white shadow-sm" style={{ backgroundColor: club.color }}>{String(index + 1).padStart(2, '0')}</span><span className="min-w-0 flex-1"><span className="flex items-center justify-between gap-2"><span className="font-serif text-lg tracking-tight">{club.name}</span><ArrowUpRight size={16} className="shrink-0 text-[#9aada8] transition-transform group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></span><span className="mt-1 block truncate text-xs text-[#81938e]">{club.address}</span><span className="mt-2 flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-[#d86f55]"><span>{club.type}</span><span className="text-[#cad5d0]">·</span><Star size={11} className="fill-[#d7aa64] text-[#d7aa64]" /> {club.rating}</span></span></button>)}</div><div className="mt-5 rounded-2xl bg-[#edf2ed] p-4"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#668080]">Currently viewing</p><p className="mt-1 font-serif text-xl">{activeClub.name}</p><p className="mt-1 text-xs text-[#81938e]">{activeClub.note}</p></div><span className="rounded-full bg-white px-2.5 py-1 text-xs text-[#668080]">{activeClub.price}</span></div><Button variant="ghost" className="mt-3 h-8 rounded-full px-0 text-xs font-semibold text-[#17343b] hover:bg-transparent hover:text-[#d86f55]">View club details <ChevronRight data-icon="inline-end" /></Button></div></aside>
        </div>
        <div id="collections" className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-3xl bg-[#17343b] p-6 text-white md:col-span-2"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#f4c8aa]">Your next invitation</p><div className="mt-8 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><h3 className="font-serif text-3xl">A better way to belong.</h3><p className="mt-2 max-w-md text-sm leading-6 text-[#b9cfca]">Let Milo curate a day around your mood, your people, and the perfect view.</p></div><Button onClick={() => document.querySelector<HTMLButtonElement>('[aria-label="Open concierge"]')?.click()} className="rounded-full bg-[#f4c8aa] text-[#17343b] hover:bg-white">Ask Milo <Sparkles data-icon="inline-end" /></Button></div></div><div className="rounded-3xl border border-[#dce5df] bg-white p-6"><CalendarDays className="text-[#d86f55]" /><p className="mt-8 text-xs font-semibold uppercase tracking-[0.18em] text-[#8ba09a]">The calendar</p><h3 className="mt-2 font-serif text-2xl">Plan your weekend</h3><p className="mt-2 text-sm leading-6 text-[#81938e]">Save the spots that feel like you.</p></div></div>
      </section>
      <Concierge clubs={clubs} onSelect={setActive} />
      {profileOpen && <div className="fixed inset-0 z-[1000] flex justify-end bg-[#17343b]/30 backdrop-blur-sm" onClick={() => setProfileOpen(false)}><section className="h-full w-full max-w-md overflow-y-auto bg-[#faf9f5] p-6 shadow-2xl md:p-9" onClick={(e) => e.stopPropagation()}><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#d86f55]">Your clubhouse</p><h2 className="mt-1 font-serif text-3xl">Profile & settings</h2></div><Button variant="ghost" size="icon" onClick={() => setProfileOpen(false)} aria-label="Close profile"><X /></Button></div><div className="mt-9 flex items-center gap-4"><div className="grid size-16 place-items-center rounded-full bg-[#dce6df] font-serif text-2xl">AR</div><div><p className="font-serif text-xl">Alex Rivera</p><p className="text-sm text-[#81938e]">alex@example.com</p></div></div><div className="mt-10 flex flex-col gap-6"><div className="rounded-2xl border border-[#dce5df] bg-white p-5"><p className="text-sm font-semibold">Account preferences</p><div className="mt-4 flex flex-col gap-4 text-sm"><label className="flex items-center justify-between">Email notifications <input type="checkbox" defaultChecked className="accent-[#d86f55]" /></label><label className="flex items-center justify-between">Personalized club picks <input type="checkbox" defaultChecked className="accent-[#d86f55]" /></label></div></div><div className="rounded-2xl border border-[#dce5df] bg-white p-5"><p className="text-sm font-semibold">Saved areas</p><p className="mt-2 text-sm text-[#81938e]">Mid-Beach, Surfside, Fisher Island</p><Button variant="outline" className="mt-4 rounded-full">Edit preferences</Button></div><Button className="rounded-full bg-[#17343b] hover:bg-[#28545b]">Sign out</Button></div></section></div>}
    </main>
  )
}
